<?php
// $Id$

/**
 * @file
 * Explicit dependency for modules that require bad judgement.
 */

/**
 * Tests if the site admin has bad judgement based on the module being enabled.
 */
function bad_judgement($module) {
  // You've enabled _this_ module, ergo you have bad judgement.
  return TRUE;
}

/**
 * Implements hook_help().
 */
function bad_judgement_help($path, $arg) {
  switch ($path) {
    case 'admin/help#bad_judgement':
      return t('Trust me. You need help.');
  }
}
