<?php
/**
 * @file
 * Explicit dependency for modules that require bad judgement.
 */

/**
 * Tests if the site admin has bad judgement based on the module being enabled.
 */
function bad_judgement($module) {
  // You've enabled _this_ module, ergo you have bad judgement.
  return TRUE;
}

/**
 * Implements hook_system_info_alter().
 */
function bad_judgement_system_info_alter(&$info, $file) {
  // Backdrop fixed the core PHP issue, so...
}
